version: "2"

services:
  cli:
    restart: always
    tty: true
    image: hyperledger/fabric-tools:1.4.1
    environment:
      - GOPATH=/opt/gopath
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ../orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ../chaincode:/opt/gopath/src/
      - ../channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
