export GOROOT=/opt/go
export GOPATH=/opt/go-lib
export BINARIESFABRICVERSION=1.4.1
export FABRICSAMPLEBINARIES=/opt/hyperledger/fabric-samples-$BINARIESFABRICVERSION/bin
PATH=$PATH:$GOROOT/bin
PATH=$PATH:$GOPATH/bin
PATH=$PATH:$FABRICSAMPLEBINARIES
